=== lanshunfang/java-class-execise-2020/src/main/resources/json-parser/books.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:complexType name="authorsType">
        <xs:sequence>
            <xs:element name="author" type="xs:token" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="BookType">

        <xs:sequence>
            <xs:element name="title" type="xs:normalizedString"/>
            <xs:element name="publishedYear" type="xs:gYear"/>
            <xs:element name="numberOfPages" type="xs:integer"/>
            <xs:element name="authors" type="authorsType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="Books">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Book" type="BookType" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== lanshunfang/java-class-execise-2020/src/main/resources/json-parser/books.xml
<?xml version = "1.0"?>
<Books xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="books.xsd">
    <Book>
        <title>21 Irrefutable Laws of Leadership</title>
        <publishedYear>1998</publishedYear>
        <numberOfPages>256</numberOfPages>
        <authors>
            <author>John C. Maxwell</author>
        </authors>
    </Book>
    <Book>
        <title>Humility</title>
        <publishedYear>1974</publishedYear>
        <numberOfPages>50</numberOfPages>
        <authors>
            <author>Andrew Murray</author>
        </authors>
    </Book>
    <Book>
        <title>Spurgeon Commentary: Galatians</title>
        <publishedYear>2014</publishedYear>
        <numberOfPages>192</numberOfPages>
        <authors>
            <author>Charles Spurgeon</author>
        </authors>
    </Book>
</Books>
